import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#F7F8FA',
    },
    scrollViewContent: {
      paddingBottom: 20,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 15,
    },
    logoContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    logoImage: {
      height: 45,
      width: 45,
    },
    brandName: {
      fontSize: 22,
      fontWeight: 'bold',
      color: '#000000',
      marginLeft: 8,
    },
    profileButton: {
      padding: 5,
    },
    greetingSection: {
      paddingHorizontal: 20,
      paddingBottom: 15,
    },
    greeting: {
      fontSize: 24,
      color: '#000000',
      fontWeight: 'bold',
    },
    greetingSubtext: {
      fontSize: 14,
      color: '#666',
      marginTop: 4,
    },
    balanceContainer: {
      backgroundColor: '#FFFFFF',
      borderRadius: 16,
      padding: 20,
      margin: 15,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 7,
    },
    balanceHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 20,
    },
    balanceLabel: {
      fontSize: 14,
      color: '#666',
      marginBottom: 8,
      fontWeight: '500',
    },
    balanceRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    balanceAmount: {
      fontSize: 36,
      fontWeight: 'bold',
      color: '#000000',
    },
    statsCurrency: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#666',
      marginLeft: 5,
    },
    eyeButton: {
      marginLeft: 10,
      padding: 5,
    },
    pointsBox: {
      backgroundColor: '#ed7b0e',
      borderRadius: 12,
      padding: 12,
      alignItems: 'center',
      minWidth: 90,
    },
    pointsValue: {
      color: '#FFFFFF',
      fontWeight: 'bold',
      fontSize: 22,
    },
    pointsLabel: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: '600',
      marginTop: 2,
    },
    actionButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    actionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 12,
      paddingVertical: 15,
      paddingHorizontal: 20,
      flex: 1,
      marginHorizontal: 5,
    },
    depositButton: {
      backgroundColor: '#ed7b0e',
    },
    withdrawButton: {
      backgroundColor: '#000000',
    },
    actionButtonText: {
      color: 'white',
      fontWeight: '600',
      marginLeft: 8,
      fontSize: 16,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      marginTop: 25,
      marginBottom: 15,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#000000',
    },
    seeAllText: {
      fontSize: 14,
      color: '#ed7b0e',
      fontWeight: '500',
    },
    cardContainer: {
      paddingHorizontal: 15,
      marginBottom: 10,
    },
    card: {
      height: 180,
      borderRadius: 16,
      padding: 20,
      backgroundColor: '#000000',
      justifyContent: 'space-between',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 5,
      },
      shadowOpacity: 0.2,
      shadowRadius: 6,
      elevation: 8,
    },
    cardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
    },
    cardLogo: {
      paddingVertical: 4,
      paddingHorizontal: 8,
      backgroundColor: '#ed7b0e',
      borderRadius: 6,
    },
    cardLogoText: {
      color: 'white',
      fontWeight: 'bold',
      fontSize: 12,
    },
    cardContent: {
      flex: 1,
      justifyContent: 'flex-end',
    },
    cardName: {
      color: 'white',
      fontSize: 18,
      fontWeight: '600',
      marginBottom: 10,
    },
    cardNumber: {
      color: 'white',
      fontSize: 16,
      marginBottom: 12,
    },
    cardType: {
      color: '#CCCCCC',
      fontSize: 12,
      fontWeight: '500',
    },
    rfidTag: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(237, 123, 14, 0.3)',
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 12,
      alignSelf: 'flex-start',
    },
    rfidText: {
      color: '#FFFFFF',
      fontWeight: '600',
      marginLeft: 4,
      fontSize: 12,
    },
    linkedCardsContainer: {
      marginBottom: 10,
    },
    linkedCardsList: {
      paddingHorizontal: 15,
    },
    linkedCardItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      padding: 15,
      marginRight: 12,
      width: 280,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 3,
    },
    linkedCardIcon: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: '#0057b8',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 15,
    },
    linkedCardInfo: {
      flex: 1,
    },
    linkedCardName: {
      fontSize: 16,
      fontWeight: '600',
      color: '#000000',
      marginBottom: 5,
    },
    linkedCardNumber: {
      fontSize: 14,
      color: '#666666',
    },
    addCardButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      padding: 15,
      marginHorizontal: 15,
      marginTop: 12,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 3,
      elevation: 2,
    },
    addCardText: {
      fontSize: 16,
      fontWeight: '600',
      color: '#ed7b0e',
      marginLeft: 10,
    },
    accountTypeSelector: {
      marginTop: 16,
    },
    promotionsList: {
      paddingHorizontal: 15,
      paddingBottom: 5,
    },
    promotionBanner: {
      width: 280,
      borderRadius: 14,
      padding: 16,
      marginRight: 15,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 3,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 5,
    },
    promotionContent: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    promotionIcon: {
      marginRight: 12,
    },
    promotionTitle: {
      color: '#FFFFFF',
      fontWeight: 'bold',
      fontSize: 16,
      marginBottom: 4,
    },
    promotionDescription: {
      color: 'rgba(255, 255, 255, 0.8)',
      fontSize: 12,
      width: 170,
    },
    tabContainer: {
      flexDirection: 'row',
      paddingHorizontal: 15,
      marginBottom: 15,
    },
    tab: {
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 20,
      marginRight: 8,
      backgroundColor: '#F0F0F0',
    },
    activeTab: {
      backgroundColor: '#ed7b0e',
    },
    tabText: {
      color: '#777',
      fontSize: 14,
      fontWeight: '500',
    },
    activeTabText: {
      color: 'white',
      fontWeight: '600',
      fontSize: 14,
    },
    transactionsList: {
      backgroundColor: 'white',
      borderRadius: 15,
      marginHorizontal: 15,
      paddingVertical: 5,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 4,
    },
    transactionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 15,
      paddingHorizontal: 15,
      borderBottomWidth: 1,
      borderBottomColor: '#F0F0F0',
    },
    transactionIcon: {
      width: 46,
      height: 46,
      borderRadius: 23,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 15,
    },
    paymentIcon: {
      backgroundColor: '#000000',
    },
    depositIcon: {
      backgroundColor: '#ed7b0e',
    },
    withdrawIcon: {
      backgroundColor: '#555555',
    },
    transactionInfo: {
      flex: 1,
    },
    transactionTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: '#000000',
      marginBottom: 4,
    },
    transactionCategory: {
      fontSize: 13,
      color: '#666',
    },
    transactionAmountContainer: {
      alignItems: 'flex-end',
    },
    transactionAmount: {
      fontSize: 16,
      fontWeight: '700',
    },
    positiveAmount: {
      color: '#ed7b0e',
    },
    negativeAmount: {
      color: '#000000',
    },
    pointsContainer: {
      backgroundColor: 'rgba(237, 123, 14, 0.1)',
      paddingVertical: 3,
      paddingHorizontal: 8,
      borderRadius: 10,
      marginTop: 4,
    },
    pointsText: {
      color: '#ed7b0e',
      fontSize: 11,
      fontWeight: '600',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'flex-end',
    },
    modalContainer: {
      backgroundColor: 'white',
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingTop: 20,
      paddingHorizontal: 20,
      paddingBottom: 30,
      maxHeight: '90%',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: 'bold',
      color: '#000000',
    },
    modalContent: {
      paddingBottom: 20,
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: '#666',
      marginBottom: 8,
      marginTop: 16,
    },
    textInput: {
      backgroundColor: '#F7F8FA',
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 14,
      fontSize: 16,
      borderWidth: 1,
      borderColor: '#E0E0E0',
    },
    rowInputs: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 5,
    },
    halfInput: {
      width: '48%',
    },
    cardTypeSelector: {
      marginTop: 16,
    },
    cardTypeOptions: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 10,
    },
    cardTypeOption: {
      alignItems: 'center',
      justifyContent: 'center',
      padding: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#E0E0E0',
      width: '30%',
    },
    selectedCardType: {
      borderColor: '#ed7b0e',
      backgroundColor: 'rgba(237, 123, 14, 0.05)',
    },
    cardTypeText: {
      marginTop: 8,
      fontSize: 14,
      color: '#777',
    },
    selectedCardTypeText: {
      marginTop: 8,
      fontSize: 14,
      color: '#ed7b0e',
      fontWeight: '600',
    },
    submitButton: {
      backgroundColor: '#ed7b0e',
      borderRadius: 12,
      paddingVertical: 16,
      alignItems: 'center',
      marginTop: 30,
    },
    submitButtonText: {
      color: 'white',
      fontSize: 18,
      fontWeight: '600',
    },
    securityNote: {
      textAlign: 'center',
      color: '#888',
      fontSize: 12,
      marginTop: 16,
      paddingHorizontal: 20,
    },
    cardDetailIcon: {
      width: 70,
      height: 70,
      borderRadius: 35,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'center',
      marginBottom: 20,
    },
    cardDetailTitle: {
      textAlign: 'center',
      fontSize: 24,
      fontWeight: 'bold',
      color: '#000000',
      marginBottom: 8,
    },
    cardDetailNumber: {
      textAlign: 'center',
      fontSize: 18,
      color: '#666',
      marginBottom: 24,
    },
    cardDetailItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#F0F0F0',
    },
    cardDetailLabel: {
      fontSize: 16,
      color: '#666',
    },
    cardDetailValue: {
      fontSize: 16,
      fontWeight: '600',
      color: '#333',
    },
    statusContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    statusDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: '#4CD964',
      marginRight: 8,
    },
    statusText: {
      color: '#4CD964',
      fontWeight: '600',
    },
    cardActions: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 10,
    },
    cardActionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 14,
      borderRadius: 12,
      backgroundColor: '#F7F8FA',
      flex: 1,
      marginHorizontal: 4,
    },
    cardActionText: {
      color: '#ed7b0e',
      fontWeight: '600',
      marginLeft: 8,
    },
    removeButton: {
      backgroundColor: 'rgba(255, 59, 48, 0.1)',
    },
    removeButtonText: {
      color: '#FF3B30',
      fontWeight: '600',
      marginLeft: 8,
    },
  });

  export default styles;